# Generated by Django 5.0.6 on 2024-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_country_alter_school_country_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='US', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
