# Generated by Django 5.0.6 on 2024-07-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='professor',
            name='directory_listing_of_professor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default='ku', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='name_of_school',
            field=models.CharField(default='tt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='terms_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='ratings.department'),
        ),
    ]
