# Generated by Django 5.0.6 on 2024-07-03 04:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_rename_name_professor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ratings_pro_search__05691d_gin'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ratings_sch_search__e73d7f_gin'),
        ),
    ]
