# Generated by Django 5.0.6 on 2024-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_professor_search_vector_school_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='professor',
            name='ratings_pro_search__05691d_gin',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='search_vector',
        ),
    ]
