# Generated by Django 5.0.6 on 2024-07-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_remove_professor_ratings_pro_search__05691d_gin_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='school',
            name='ratings_sch_search__e73d7f_gin',
        ),
        migrations.RemoveField(
            model_name='school',
            name='search_vector',
        ),
    ]
