# Generated by Django 5.0.6 on 2024-07-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_schoolrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ProfessorsTag',
        ),
    ]
