# Generated by Django 5.0.6 on 2024-07-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_rename_tag_professorstag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorstag',
            name='professor',
        ),
    ]
