# Generated by Django 5.0.6 on 2024-07-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_remove_professorstag_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('is_online_course', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('is_take_professor_again', models.BooleanField()),
                ('was_class_taken_for_credit', models.BooleanField(blank=True, null=True)),
                ('was_use_textbook', models.BooleanField(blank=True, null=True)),
                ('was_attendance_mandatory', models.BooleanField(null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.professor')),
            ],
        ),
    ]
