# Generated by Django 5.0.6 on 2024-07-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_professorrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorrating',
            name='tags',
        ),
        migrations.AddField(
            model_name='professorrating',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ratings.professorstag'),
        ),
    ]
