# Generated by Django 5.0.6 on 2024-09-13 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_remove_professorrating_tags_professorrating_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professorrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Ok'), (3, 'Good'), (4, 'Great'), (5, 'Awesome')]),
        ),
    ]
