# Generated by Django 5.0.6 on 2024-09-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0019_alter_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
