# Generated by Django 5.0.6 on 2024-09-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0022_remove_professor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='ratings.department'),
        ),
    ]
