# Generated by Django 5.0.6 on 2024-08-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='user',
        ),
    ]
